language: shell

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi

install: true

script:
  - shellcheck -e SC1090,SC1091 .zshrc
  - shellcheck -e SC1091 .prefs/mac.sh
  - shellcheck .prefs/ubuntu.sh
  - shellcheck .prefs/unix.sh
  - shellcheck bash/ccq
  - shellcheck bash/jar2txt
  - shellcheck bash/update_root_gradle

branches:
  except:
    - gh-pages

notifications:
  email: false
